name: CI/CD Pipeline with K8s

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: docker build -t flask-devops-demo .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: |
        docker tag flask-devops-demo ${{ secrets.DOCKER_USERNAME }}/flask-devops-demo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-devops-demo:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Verify Pods and Services
      run: |
        kubectl get pods
        kubectl get svc
